name: verovio_integration
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^11.0.0

flutter:
  uses-material-design: true

ffigen:
  output: 'lib/verovio/generated_bindings.dart'
  name: 'VerovioWrapper'
  description: 'Verovio C Library wrapper for Dart'
  functions:
    expose-typedefs:
      include:
        - '.*'
  headers:
    entry-points:
      - 'lib/verovio/c_wrapper.h'
    include-directives:
      - '**c_wrapper.h'
      - '**c_wrapper.cpp'
